# Generated by Django 3.1.1 on 2021-03-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_movielinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
