# Generated by Django 3.1.1 on 2021-03-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_trailer',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
